### ISSUE TITLE
Potential security bug in custom varint code

### ISSUE THREAD

**Issue by dwlnetnl** [gate-computer/wag#18]
As preface: I am not a user nor had any knowledge of the existence of this project until I came across it in a [blog](https://philpearl.github.io/post/reader/) post.

Recently there is a security related bug fixed in the standard library regarding varints. It seems that at this moment in time the version within this code base hasn't been updated. I am merely putting this issue down as a gentle nudge.

Commit that fixes the bug in the standard library: https://github.com/golang/go/commit/027d7241ce050d197e7fabea3d541ffbe3487258

**Comment by tsavola** [comment]
Thank you for reporting this, @dwlnetnl!

**Comment by dwlnetnl** [comment]
No worries, I'm glad it's helpful, didn't want to come across like an arse.
